### ISSUE TITLE
obd_demo usage

### ISSUE THREAD

**Issue by ikoc** [Longan-Labs/Serial_CAN_Arduino#1]
Hello ,

I have OBD-II CAN-BUS Development Kit. I have prepared kit as in the instructions. Compile and upload the code to the arduino.

When I power on my arduino by plugging usb to pc , if obd2 connected to vehicle , serial monitor wont show any message, If obd2 is not connected serial monitor says 

15:11:24.153 -> set can rate ok
15:11:24.856 -> set mask ok
15:11:27.341 -> set filt ok
15:11:27.341 -> begin

after it says begin i plug obd2 socket to the vehicle (opel astra 2013 sedan ) 
when i send 
15:27:54.128 -> SEND PID: 0xC
15:27:54.175 -> 
15:27:54.175 -> ------------------------------------------------------------------
15:27:54.175 -> Get Data From id: 0x7E8
15:27:54.175 -> 
15:28:05.368 -> SEND PID: 0xD
15:28:05.415 -> 
15:28:05.415 -> ------------------------------------------------------------------
15:28:05.415 -> Get Data From id: 0x7E8
15:28:05.415 -> 
15:28:12.399 -> SEND PID: 0x5
15:28:12.446 -> 
15:28:12.446 -> ------------------------------------------------------------------
15:28:12.446 -> Get Data From id: 0x7E8
15:28:12.446 -> 

It show me these responses. How can it get speed , rpm values ?

And why should i need to unplug obd2 connector to make connection well.

**Comment by ikoc** [comment]
The first problem has solved when i tried with different car.  But I still cannot get speed , rpm values or any other information.  What does "Get Data From id: 0x7E8 "this mean?

**Comment by stephen1874** [comment]
> The first problem has solved when i tried with different car. But I still cannot get speed , rpm values or any other information. What does "Get Data From id: 0x7E8 "this mean?

Hello, 0x7E8 is id of your ECU, there's a bug in the code, at line 136, change len to 8.
Please have a try.
Thanks.

**Comment by ikoc** [comment]
It works like a charm. Thank you .
